### ISSUE TITLE
Setting onsite coupling to zero doesn't remove it

### ISSUE THREAD

**Issue by Lazersmoke** [SunnySuite/Sunny.jl#110]
https://github.com/SunnySuite/Sunny.jl/blob/188846860b8fb6a447f8400f854311c340003b68/src/System/OnsiteCoupling.jl#L144

I use this in parameter sweeps, where `set_onsite_coupling!(sys, <zero matrix>, 1)` goes after `set_onsite_coupling!(sys, +0.1 * Sz^2, 1)` and should remove that coupling

**Comment by kbarros** [comment]
Agreed.
