### ISSUE TITLE
Higher resolution images in docs

### ISSUE THREAD

**Issue by kbarros** [SunnySuite/Sunny.jl#137]
The GLMakie-generated images are currently low-resolution.

Once GLMakie 0.20 is released, it should be possible to increase the resolution without affecting the sizes of the line widths, text labels, etc.

At that point, maybe we can increase resolution by modifying the parameter `'-screen 0 1024x768x24'` in the `builddocs.yml` file?

**Comment by Lazersmoke** [comment]
Are they particularly low resolution? I haven't seen any resolution problem with them

**Comment by kbarros** [comment]
Some discussion here: https://github.com/MakieOrg/Makie.jl/issues/3184#issuecomment-1694590574

> Actually, the size of GLMakie is already the "correct" one here (in terms of logical pixel size), it just doesn't look too good because the image is rendered with pixel density 1. In the beta, both WGLMakie and GLMakie should have the size of the currently blurry image, but you should be able to make both sharp.

The fix should be coming with Makie 0.20.
