### ISSUE TITLE
`spin_operators` / 'stevens_operators' not defined

### ISSUE THREAD

**Issue by ilijanikolov** [SunnySuite/Sunny.jl#138]
I have imported using Sunny, GLMakie, LinearAlgebra

and I keep getting the error message:
UndefVarError: `spin_operators` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:31

ERROR: UndefVarError: `stevens_operators` not defined
Stacktrace:
 [1] top-level scope

Using Sunny 0.4.3, Julia 1.9.2

**Comment by kbarros** [comment]
This is a new feature of Sunny 0.5. From the Julia prompt you should be able to enter the package manager with `]` and then type `update Sunny` to get the latest version. Please let us know how it goes.

**Comment by kbarros** [comment]
Actual, there was a snag with the 0.5.0 release. Will let you know when it's fixed.

**Comment by kbarros** [comment]
The registration finally went through. You should be able to `] update` to Sunny 0.5.0 now.

**Comment by ilijanikolov** [comment]
Thank you! It seems to be working now. Although I did get this error during update 
 1 dependency had warnings during precompilation:
┌ LinearMapsChainRulesCoreExt [80cc3b07-7966-5fa1-b050-64b4b3e87554]
│  ┌ Error: Error during loading of extension LinearMapsSparseArraysExt of LinearMaps, use `Base.retry_load_extensions()` to retry.
│  │   exception =
│  │    1-element ExceptionStack

Thanks!

**Comment by kbarros** [comment]
Glad it worked. Not sure about that reported error with LinearMaps. Sometimes it's a bit of a dance to get Julia to recognize all the packages. Usually an `] update` will fix things. Feel free to ask again if more problems show up.
