### ISSUE TITLE
Build IJulia notebook for each doc example

### ISSUE THREAD

**Issue by kbarros** [SunnySuite/Sunny.jl#144]
Each example in the docs should contain a link to a corresponding IJulia notebook. The latter should be automatically built in our "build docs" Github action.

Relative to the markdown docs, IJulia notebooks should:

* Use WGLMakie if in IJulia environment
* Have appropriate default resolution
* Have the correct shade of gray for spins (perhaps this WGLMakie bug could be fixed?)
* Have appropriate size of axis labels (this might get easier with Makie 0.20)
* Generate the correct HTML for image links

Also, as part of the refresh, we should deal with `#hide` pragmas so that notebooks are fully executable.

**Comment by kbarros** [comment]
This feature might depend on issues in other packages, e.g.:
https://github.com/MakieOrg/Makie.jl/issues/3184
https://github.com/fredrikekre/Literate.jl/issues/222

**Comment by Lazersmoke** [comment]
If Literate can target IJulia, then surely it handles the hide tags correctly?
