### ISSUE TITLE
Integration assistance

### ISSUE THREAD

**Issue by ddahlbom** [SunnySuite/Sunny.jl#149]
Provide:
1) Function to analyze `Langevin` time step
2) Function to analyze `ImplicitMidpoint` time step
3) Function to estimate decorrelation times
4) Functions to output samples and trajectories in newly allocated arrays
5) Tutorial demonstrating use of the above

**Comment by kbarros** [comment]
Regarding 1 and 2, work is in progress here: https://github.com/SunnySuite/Sunny.jl/pull/208

Regarding 3, I wonder if we can leverage one of these packages:

- https://github.com/m3g/BlockAverage.jl
- https://github.com/carstenbauer/BinningAnalysis.jl

**Comment by kbarros** [comment]
Closing this as completed following https://github.com/SunnySuite/Sunny.jl/pull/208. We could still use a tutorial to illustrate [BinningAnalysis](https://github.com/carstenbauer/BinningAnalysis.jl), but that seems independent of immediate Sunny development.
