### ISSUE TITLE
Basic Exact Diagonalization

### ISSUE THREAD

**Issue by ddahlbom** [SunnySuite/Sunny.jl#170]
1) Add functions for constructing full, sparse Hamiltonian from Sunny `System`
2) Functions for generating full basis and bases associated to symmetry-specific sectors (e.g. magnetization)
3) Choose and incorporate existing diagonalization library (e.g., KrylovKit)
4) S(q,w) with continued faction approach

**Comment by kbarros** [comment]
This will be a very nice tool. Candidate for development in SunnyContributed?

**Comment by ddahlbom** [comment]
Sure, seems reasonable to work there. Will close here for now.
