### ISSUE TITLE
Can sunny do constant-energy cut simulation？

### ISSUE THREAD

**Issue by HyoukaChitandaEru** [SunnySuite/Sunny.jl#274]
Dear Sunny development team, can sunny do constant-energy cut simulation？
Sorry, I didn't find code related to constant-energy cut simulation in example folder.

**Comment by kbarros** [comment]
Hello @HyoukaChitandaEru, constant energy cuts can be extracted from the full dynamical structure calculations. I am not sure if it's documented well, but there are some examples on binned data at the bottom of this page: https://sunnysuite.github.io/Sunny.jl/dev/examples/04_GSD_FeI2.html

For more discussion, please join our Slack server with this link:
https://join.slack.com/t/sunny-users/shared_invite/zt-1otxwwko6-LzPtp7Fazkjx2XEqfgKqtA

Questions like this are great for the #helpdesk channel on Slack.
