### ISSUE TITLE
Allow for inhomogeneities in real-space

### ISSUE THREAD

**Issue by kbarros** [SunnySuite/Sunny.jl#38]
Two overlapping feature requests:

1. Allow to randomly "disable" interactions for certain magnetic ions. I think it's common for a material to have some occupancy fraction of the magnetic ions, and with a large enough unit cell, we could stochastically sample from it.
2. Allow to apply a localized field. Eventually, people will probably want to control both space and time dependence of the applied field. I guess, similarly, people might want to apply localized electric currents.

We should brainstorm what the interface for this should look like. For example, exchange interactions are currently embedded into a `HamiltonianCPU` object or (later) will be compiled into a `HamiltonianGPU`. If the user changes them, we will need to a careful way to update all the state.

**Comment by kbarros** [comment]
Amirreza wants to be able to specify nonzero exchange interactions for disordered sites. We can do this if we require the user to manually specify every single exchange interactions. But having Sunny support for symmetry-propagation of interactions becomes tricky. See, for example, this figure.

![image](https://user-images.githubusercontent.com/290205/195371298-6ae6459c-4529-413a-bbc8-0c899b721ae3.png)

**Comment by amirhemmatzade** [comment]
Hi,

For cases which the disorder is not local in the cell and essentially everywhere, what would be the better way to approach? Probably one cannot benefit from symmetries because defining the symmetry operators will be very complicated/just not possible.

Thanks

**Comment by kbarros** [comment]
Our plan is to allow the user to specify exchange interactions directly on individual bounds. We have a plan to implement this as part of a major overhaul of Sunny. It's hard to give a time estimate because it depends on how much we get interrupted by other priorities. I will update this issue.

**Comment by kbarros** [comment]
This is resolved with https://github.com/SunnySuite/Sunny.jl/pull/59.
