### ISSUE TITLE
Minor improvement to comments / docs for Symmetry/AllowedCouplings.jl

### ISSUE THREAD

**Issue by ColeMiles** [SunnySuite/Sunny.jl#5]
The current comment at the top of `Symmetry/AllowedCouplings.jl` is a bit confusing -- it seems to imply that the constraints on allowed exchange matrices are:

$J = R J R^T$

for _all_ R that map bonds within a symmetry equivalency class. But these constraints are only for R which map bonds to themselves.

Maybe as part of this issue, a new section in the "Internals" documentation could be made which explains the ideas of the symmetry analysis and how the algorithms work?

**Comment by kbarros** [comment]
Partially addressed in Commit https://github.com/MagSims/Sunny.jl/commit/ec0d584c7ef97db6868611373870f0dba90499be

Helped wanted to split this out into a nice Markdown document.

**Comment by kbarros** [comment]
I think the current code comments are good. Comprehensive markdown docs would of course be better, but that will require a separate effort.
