### ISSUE TITLE
Fix markersize in plotting legends

### ISSUE THREAD

**Issue by ColeMiles** [SunnySuite/Sunny.jl#7]
In all plotting functions which plot a lattice, we often have to use a very large `markersize` to get the atoms to appear reasonably large. However, then any legends are completely covered up by an incredibly large circle.

Possible fixes are to either find how to manually set the marker size in the legend to be different than the `markersize` plotted, or to have plotting functions plot in a different set of scaled-down coordinates so that reasonable marker sizes can be used.

**Comment by kbarros** [comment]
Closing for now because this plotting code is no longer exposed, and the underlying sizing issues might be fixed in Makie 0.20.
